name: Deploy Next
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: weekly-app
          environment_name: Weekly-app-env
          existing_bucket_name: elasticbeanstalk-us-east-1-786009993834
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
